### ISSUE TITLE
Awkward transition between fragments

### ISSUE THREAD

**Issue by abuagarwal** [sunzhaoyuan/RoseChatApp#8]
When I am in Messages and I go to Profile, I also go through Contacts. This feels awkward and should be corrected so I go straight to Profile. Similarly when I am in Messages and I click on Settings, I go through both Contacts and Profile.

**Comment by sunzhaoyuan** [comment]
This is because I need to add(initiate) them in a specific order in ViewPager when the MainActivity calls onCreate. But I think we can find a way to solve it.

Although I think it makes sense that you will need to go through Contacts if you go from Message to Profile. That is the order of our bottom navigation buttons, right? I agree this is an issue for Settings since it does not belong to the "three main screens".

**Comment by sunzhaoyuan** [comment]
I think we've solved this issue. Referring the solution of issue #10 .
